const List surah = [
  {
    "id": 1,
    "name": "Al Fatiha",
    "aya": 7,
    "english": "The Opening",
    "turkish": "Fâtiha",
    "french": "L'ouverture",
    "indonesian": "Pembukaan",
    "malay": "Pembukaan",
    "urdu": "সূচনা",
    "bengali": "کھولنے والی",
    "place": "Makkah",
    "arabic": "الفاتحة"
  },
  {
    "id": 2,
    "name": "Al Baqarah",
    "aya": 286,
    "english": "The Cow",
    "turkish": "Bakara",
    "french": "La Vache",
    "indonesian": "Sapi Betina",
    "malay": "Lembu Betina",
    "urdu": "বকনা-বাছুর",
    "bengali": "گائے",
    "place": "Madinah",
    "arabic": "البقرة"
  },
  {
    "id": 3,
    "name": "Al Imran",
    "aya": 200,
    "english": "The Family of Imran",
    "turkish": "Âl-i İmrân",
    "french": "La famille D'Imran",
    "indonesian": "Keluarga Imran",
    "malay": "Keluarga Imran",
    "urdu": "ইমরানের পরিবার",
    "bengali": "عمران کا خاندان",
    "place": "Madinah",
    "arabic": "آل عمران"
  },
  {
    "id": 4,
    "name": "An Nisa",
    "aya": 176,
    "english": "The Women",
    "turkish": "Nisâ",
    "french": "Les femmes",
    "indonesian": "Wanita",
    "malay": "Wanita",
    "urdu": "নারী",
    "bengali": "عورت",
    "place": "Madinah",
    "arabic": "النساء"
  },
  {
    "id": 5,
    "name": "Al Ma'idah",
    "aya": 120,
    "english": "The Table",
    "turkish": "Mâide",
    "french": "La table servie",
    "indonesian": "Jamuan (Hidangan Makanan)",
    "malay": "Hidangan",
    "urdu": "খাদ্য পরিবেশিত টেবিল",
    "bengali": "دسترخوان",
    "place": "Madinah",
    "arabic": "المائدة"
  },
  {
    "id": 6,
    "name": "Al An'am",
    "aya": 165,
    "english": "The Cattle",
    "turkish": "En'âm",
    "french": "Les bestiaux",
    "indonesian": "Binatang Ternak",
    "malay": "Binatang Ternakan",
    "urdu": "গৃহপালিত পশু",
    "bengali": "مویشی",
    "place": "Makkah",
    "arabic": "الأنعام"
  },
  {
    "id": 7,
    "name": "Al A'raf",
    "aya": 206,
    "english": "The Heights",
    "turkish": "A'râf",
    "french": "Les murailles",
    "indonesian": "Tempat-tempat Tinggi",
    "malay": "Tempat Tertinggi",
    "urdu": "উচু স্থান",
    "bengali": "اونچی جگہ",
    "place": "Makkah",
    "arabic": "الأعراف"
  },
  {
    "id": 8,
    "name": "Al Anfal",
    "aya": 75,
    "english": "The Spoils of War",
    "turkish": "Enfâl",
    "french": "Le butin",
    "indonesian": "Rampasan Perang",
    "malay": "Rampasan Perang",
    "urdu": "যুদ্ধ-লব্ধ ধনসম্পদ",
    "bengali": "مال غنیمت",
    "place": "Madinah",
    "arabic": "الأنفال"
  },
  {
    "id": 9,
    "name": "At Tawbah",
    "aya": 129,
    "english": "The Repentance",
    "turkish": "Tevbe",
    "french": "Le repentir",
    "indonesian": "Pengampunan",
    "malay": "Pengampunan",
    "urdu": "অনুশোচনা",
    "bengali": "توبہ",
    "place": "Madinah",
    "arabic": "التوبة"
  },
  {
    "id": 10,
    "name": "Al Yunus",
    "aya": 109,
    "english": "Jonah",
    "turkish": "Yûnus",
    "french": "Jonas",
    "indonesian": "Yunus",
    "malay": "Nabi Yunus a.s.",
    "urdu": "নবী ইউনুস",
    "bengali": "یونس",
    "place": "Makkah",
    "arabic": "يونس"
  },
  {
    "id": 11,
    "name": "Hud",
    "aya": 123,
    "english": "Hud",
    "turkish": "Hûd",
    "french": "Hud",
    "indonesian": "Hud",
    "malay": "Nabi Hud a.s.",
    "urdu": "নবী হুদ",
    "bengali": "حود",
    "place": "Makkah",
    "arabic": "هود"
  },
  {
    "id": 12,
    "name": "Yusuf",
    "aya": 111,
    "english": "Joseph",
    "turkish": "Yûsuf",
    "french": "Joseph",
    "indonesian": "Yusuf",
    "malay": "Nabi Yusuf a.s.",
    "urdu": "নবী ইউসুফ",
    "bengali": "یوسف",
    "place": "Makkah",
    "arabic": "يوسف"
  },
  {
    "id": 13,
    "name": "Ar Ra'd",
    "aya": 43,
    "english": "The Thunder",
    "turkish": "Ra'd",
    "french": "Le tonnerre",
    "indonesian": "Guruh (Petir)",
    "malay": "Guruh",
    "urdu": "বজ্রপাত",
    "bengali": "گرج",
    "place": "Madinah",
    "arabic": "الرعد"
  },
  {
    "id": 14,
    "name": "Ibrahim",
    "aya": 52,
    "english": "Abraham",
    "turkish": "İbrâhîm",
    "french": "Abraham",
    "indonesian": "Ibrahim",
    "malay": "Nabi Ibrahim a.s.",
    "urdu": "নবী ইবরাহীম",
    "bengali": "ابراہیم",
    "place": "Makkah",
    "arabic": "ابراهيم"
  },
  {
    "id": 15,
    "name": "Al Hijr",
    "aya": 99,
    "english": "The Stoneland",
    "turkish": "Hicr",
    "french": "Le chemin rocailleux",
    "indonesian": "Bukit",
    "malay": "Kawasan Berbatu",
    "urdu": "পাথুরে পাহাড়",
    "bengali": "پتھر",
    "place": "Makkah",
    "arabic": "الحجر"
  },
  {
    "id": 16,
    "name": "An Nahl",
    "aya": 128,
    "english": "The Honey Bee",
    "turkish": "Nahl",
    "french": "Les abeilles",
    "indonesian": "Lebah Madu",
    "malay": "Lebah",
    "urdu": "মৌমাছি",
    "bengali": "شہد کی مکھی",
    "place": "Makkah",
    "arabic": "النحل"
  },
  {
    "id": 17,
    "name": "Al Isra'",
    "aya": 111,
    "english": "The Night Journey",
    "turkish": "İsrâ",
    "french": "Le voyage nocturne",
    "indonesian": "Perjalanan Malam",
    "malay": "Perjalanan Malam",
    "urdu": "ইহুদি জাতি",
    "bengali": "رات کا صفر",
    "place": "Makkah",
    "arabic": "الإسراء"
  },
  {
    "id": 18,
    "name": "Al Kahf",
    "aya": 110,
    "english": "The Cave",
    "turkish": "Kehf",
    "french": "La caverne",
    "indonesian": "Para Penghuni Gua",
    "malay": "Gua",
    "urdu": "গুহা",
    "bengali": "غار",
    "place": "Makkah",
    "arabic": "الكهف"
  },
  {
    "id": 19,
    "name": "Maryam",
    "aya": 98,
    "english": "Mary",
    "turkish": "Meryem",
    "french": "Marie",
    "indonesian": "Maryam",
    "malay": "Siti Maryam",
    "urdu": "মারইয়াম (ঈসা নবীর মা)",
    "bengali": "مریم",
    "place": "Makkah",
    "arabic": "مريم"
  },
  {
    "id": 20,
    "name": "Ta Ha",
    "aya": 135,
    "english": "Ta Ha",
    "turkish": "Tâhâ",
    "french": "Ta-Ha",
    "indonesian": "Tha-Ha",
    "malay": "Taahaa",
    "urdu": "ত়া হা",
    "bengali": "طٰہٰ",
    "place": "Makkah",
    "arabic": "طه"
  },
  {
    "id": 21,
    "name": "Al Anbiya",
    "aya": 112,
    "english": "The Prophets",
    "turkish": "Enbiyâ",
    "french": "Les prophètes",
    "indonesian": "Para Nabi",
    "malay": "Para Nabi",
    "urdu": "নবীগণ",
    "bengali": "پیغمبر",
    "place": "Makkah",
    "arabic": "الأنبياء"
  },
  {
    "id": 22,
    "name": "Al Hajj",
    "aya": 78,
    "english": "The Pilgrimage",
    "turkish": "Hac",
    "french": "Le pèlerinage",
    "indonesian": "Haji",
    "malay": "Haji",
    "urdu": "হ়াজ্জ",
    "bengali": "حج",
    "place": "Madinah",
    "arabic": "الحج"
  },
  {
    "id": 23,
    "name": "Al Mu minun",
    "aya": 118,
    "english": "The Believers",
    "turkish": "Mü'minûn",
    "french": "Les croyants",
    "indonesian": "Orang-orang Mukmin",
    "malay": "Golongan yang Beriman",
    "urdu": "বিশ্বাসী",
    "bengali": "مومنین",
    "place": "Makkah",
    "arabic": "المؤمنون"
  },
  {
    "id": 24,
    "name": "An Nur",
    "aya": 64,
    "english": "The Light",
    "turkish": "Nûr",
    "french": "La lumière",
    "indonesian": "Cahaya",
    "malay": "Cahaya",
    "urdu": "আলো",
    "bengali": "نور",
    "place": "Madinah",
    "arabic": "النور"
  },
  {
    "id": 25,
    "name": "Al Furqan",
    "aya": 77,
    "english": "The Criterion",
    "turkish": "Furkân",
    "french": "Le discernement",
    "indonesian": "Pembeda",
    "malay": "Pembeza Kebenaran dan Kebatilan",
    "urdu": "মানদণ্ড",
    "bengali": "صحیح اور غلط میں فرق کرنے والی کتاب",
    "place": "Makkah",
    "arabic": "الفرقان"
  },
  {
    "id": 26,
    "name": "As Su'ara",
    "aya": 227,
    "english": "The Poets",
    "turkish": "Şuarâ",
    "french": "Les poètes",
    "indonesian": "Penyair",
    "malay": "Para Penyair",
    "urdu": "কবি",
    "bengali": "شعراٗ",
    "place": "Makkah",
    "arabic": "الشعراء"
  },
  {
    "id": 27,
    "name": "An Naml",
    "aya": 93,
    "english": "The Ant",
    "french": "Les fourmis",
    "turkish": "Neml",
    "indonesian": "Semut",
    "malay": "Semut",
    "urdu": "পিঁপড়া",
    "bengali": "چیونٹی",
    "place": "Makkah",
    "arabic": "النمل"
  },
  {
    "id": 28,
    "name": "Al Qasas",
    "aya": 88,
    "english": "The Narrations",
    "turkish": "Kasas",
    "french": "Le récit",
    "indonesian": "Kisah-kisah",
    "malay": "Cerita-cerita",
    "urdu": "কাহিনি",
    "bengali": "قصے",
    "place": "Makkah",
    "arabic": "القصص"
  },
  {
    "id": 29,
    "name": "Al Ankabut",
    "aya": 69,
    "english": "The Spider",
    "turkish": "Ankebût",
    "french": "L'araignée",
    "indonesian": "Laba-laba",
    "malay": "Labah-labah",
    "urdu": "মাকড়শা",
    "bengali": "مکڑی",
    "place": "Makkah",
    "arabic": "العنكبوت"
  },
  {
    "id": 30,
    "name": "Ar Rum",
    "aya": 60,
    "english": "Rome",
    "turkish": "Rûm",
    "french": "Les romains",
    "indonesian": "Bangsa Romawi",
    "malay": "Bangsa Rom",
    "urdu": "রোমান জাতি",
    "bengali": "روم",
    "place": "Makkah",
    "arabic": "الروم"
  },
  {
    "id": 31,
    "name": "Luqman",
    "aya": 34,
    "english": "Luqman",
    "turkish": "Lokmân",
    "french": "Luqman",
    "indonesian": "Luqman",
    "malay": "Luqman",
    "urdu": "এক জ্ঞানী ব্যাক্তি",
    "bengali": "لقمان",
    "place": "Makkah",
    "arabic": "لقمان"
  },
  {
    "id": 32,
    "name": "As Sajdah",
    "aya": 30,
    "english": "The Prostration",
    "turkish": "Secde",
    "french": "La prosternation",
    "indonesian": "Sujud",
    "malay": "Sujud",
    "urdu": "সিজদা",
    "bengali": "سجدہ",
    "place": "Makkah",
    "arabic": "السجدة"
  },
  {
    "id": 33,
    "name": "Al Ahzab",
    "aya": 73,
    "english": "The Clans",
    "turkish": "Ahzâb",
    "french": "Les coalisés",
    "indonesian": "Golongan yang Bersekutu",
    "malay": "Golongan yang Bersekutu",
    "urdu": "জোট",
    "bengali": "متحد گروہ",
    "place": "Madinah",
    "arabic": "الأحزاب"
  },
  {
    "id": 34,
    "name": "Saba'",
    "aya": 54,
    "english": "Sheba",
    "turkish": "Sebe'",
    "french": "Saba",
    "indonesian": "Saba\\'",
    "malay": "Kaum Saba’",
    "urdu": "রানী সাবা/শেবা",
    "bengali": "سبا",
    "place": "Makkah",
    "arabic": "سبإ"
  },
  {
    "id": 35,
    "name": "Fatir",
    "aya": 45,
    "english": "The Originator",
    "turkish": "Fâtır",
    "french": "Le créateur",
    "indonesian": "Pencipta",
    "malay": "Pencipta",
    "urdu": "আদি স্রষ্টা",
    "bengali": "پیدا کرنے والا",
    "place": "Makkah",
    "arabic": "فاطر"
  },
  {
    "id": 36,
    "name": "Ya'sin",
    "aya": 83,
    "english": "Ya Sin",
    "turkish": "Yâsîn",
    "french": "Ya Sin",
    "indonesian": "Yas Sin",
    "malay": "Yaasin",
    "urdu": "ইয়াসীন",
    "bengali": "یٰسٓ",
    "place": "Makkah",
    "arabic": "يس"
  },
  {
    "id": 37,
    "name": "As Saffat",
    "aya": 182,
    "english": "Those Who Set The Ranks",
    "turkish": "Sâffât",
    "french": "Les rangées",
    "indonesian": "Barisan-barisan",
    "malay": "Yang Teratur Berbaris",
    "urdu": "সারিবদ্ধভাবে দাঁড়ানো",
    "bengali": "صف باندھنے والے",
    "place": "Makkah",
    "arabic": "الصافات"
  },
  {
    "id": 38,
    "name": "Saad",
    "aya": 88,
    "english": "Ṣād",
    "turkish": "Sâd",
    "french": "Ṣād",
    "indonesian": "Shad",
    "malay": "Saad",
    "urdu": "আরবি বর্ণ সাদ",
    "bengali": "صٓ",
    "place": "Makkah",
    "arabic": "ص"
  },
  {
    "id": 39,
    "name": "Az Zumar",
    "aya": 75,
    "english": "The Crowds",
    "turkish": "Zümer",
    "french": "Les groupes",
    "indonesian": "Para Rombongan",
    "malay": "Rombongan",
    "urdu": "দলবদ্ধ জনতা",
    "bengali": "گروہ",
    "place": "Makkah",
    "arabic": "الزمر"
  },
  {
    "id": 40,
    "name": "Ghafir",
    "aya": 85,
    "english": "The Forgiver",
    "turkish": "Mü'min",
    "french": "Le pardonneur",
    "indonesian": "Sang Maha Pengampun",
    "malay": "Orang yang Beriman",
    "urdu": "ক্ষমাকারী",
    "bengali": "بخشنے والا",
    "place": "Makkah",
    "arabic": "غافر"
  },
  {
    "id": 41,
    "name": "Fussilat",
    "aya": 54,
    "english": "Expounded",
    "turkish": "Fussilet",
    "french": "Les versets détaillés",
    "indonesian": "Yang Dijelaskan",
    "malay": "Dijelaskan",
    "urdu": "সুস্পষ্ট বিবরণ",
    "bengali": "مفصل",
    "place": "Makkah",
    "arabic": "فصلت"
  },
  {
    "id": 42,
    "name": "As Sura",
    "aya": 53,
    "english": "The Consultation",
    "turkish": "Şûrâ",
    "french": "La consultation",
    "indonesian": "Musyawarah",
    "malay": "Permesyuaratan",
    "urdu": "পরামর্শ",
    "bengali": "شورٰی",
    "place": "Makkah",
    "arabic": "الشورى"
  },
  {
    "id": 43,
    "name": "Az Zukhruf",
    "aya": 89,
    "english": "The Gold Adornments",
    "turkish": "Zuhruf",
    "french": "L'ornement",
    "indonesian": "Perhiasan",
    "malay": "Perhiasan Emas",
    "urdu": "সোনাদানা",
    "bengali": "سونے کی چمک",
    "place": "Makkah",
    "arabic": "الزخرف"
  },
  {
    "id": 44,
    "name": "Ad Dukhan",
    "aya": 59,
    "english": "The Smoke",
    "turkish": "Duhân",
    "french": "La fumée",
    "indonesian": "Kabut",
    "malay": "Kabut / Asap",
    "urdu": "ধোঁয়া",
    "bengali": "دھواں",
    "place": "Makkah",
    "arabic": "الدخان"
  },
  {
    "id": 45,
    "name": "Al Jaathiyah",
    "aya": 37,
    "english": "The Kneeling Down",
    "turkish": "Câsiye",
    "french": "L'agenouillée",
    "indonesian": "Yang Bertekuk Lutut",
    "malay": "Yang Berlutut",
    "urdu": "নতজানু",
    "bengali": "زانوٗوں کے بل گری ہوئی",
    "place": "Makkah",
    "arabic": "الجاثية"
  },
  {
    "id": 46,
    "name": "Al Ahqaf",
    "aya": 35,
    "english": "Winding Sand tracts",
    "turkish": "Ahkâf",
    "french": "Les dunes",
    "indonesian": "Bukit-bukir Pasir",
    "malay": "Bukit-bukit Pasir",
    "urdu": "বালুর পাহাড়",
    "bengali": "ریگستان",
    "place": "Makkah",
    "arabic": "الأحقاف"
  },
  {
    "id": 47,
    "name": "Muhammad",
    "aya": 38,
    "english": "Muhammad",
    "turkish": "Muhammed",
    "french": "Muhammed",
    "indonesian": "Muhammad",
    "malay": "Nabi Muhammad SAW",
    "urdu": "নবী মুহাম্মদ",
    "bengali": "محمدﷺ",
    "place": "Madinah",
    "arabic": "محمد"
  },
  {
    "id": 48,
    "name": "Al Fath",
    "aya": 29,
    "english": "The Victory",
    "turkish": "Fetih",
    "french": "La victoire éclatante",
    "indonesian": "Kemenangan",
    "malay": "Kemenangan",
    "urdu": "বিজয়",
    "bengali": "فتح",
    "place": "Madinah",
    "arabic": "الفتح"
  },
  {
    "id": 49,
    "name": "Al Hujurut",
    "aya": 18,
    "english": "The Private Apartments",
    "turkish": "Hucurât",
    "french": "Les appartements",
    "indonesian": "Kamar-kamar",
    "malay": "Bilik-bilik",
    "urdu": "আবাস",
    "bengali": "حجرے",
    "place": "Madinah",
    "arabic": "الحجرات"
  },
  {
    "id": 50,
    "name": "Qaaf",
    "aya": 45,
    "english": "Q̈āf",
    "turkish": "Kâf",
    "french": "Q̈āf",
    "indonesian": "Qaf",
    "malay": "Qaaf",
    "urdu": "কাফ",
    "bengali": "قٓ",
    "place": "Makkah",
    "arabic": "ق"
  },
  {
    "id": 51,
    "name": "Ad Dariyat",
    "aya": 60,
    "english": "The Wind That Scatter",
    "turkish": "Zâriyât",
    "french": "Qui éparpillent",
    "indonesian": "Angin yang Menerbangkan",
    "malay": "Angin yang Menerbangkan",
    "urdu": "বিক্ষেপকারী বাতাস",
    "bengali": "بکھیرنے والیاں",
    "place": "Makkah",
    "arabic": "الذاريات"
  },
  {
    "id": 52,
    "name": "At Toor",
    "aya": 49,
    "english": "The Mount",
    "turkish": "Tûr",
    "french": "At-Tur",
    "indonesian": "Bukit",
    "malay": "Bukit",
    "urdu": "পাহাড়",
    "bengali": "طور پہاڑ",
    "place": "Makkah",
    "arabic": "الطور"
  },
  {
    "id": 53,
    "name": "An Najm",
    "aya": 62,
    "english": "The Star",
    "turkish": "Necm",
    "french": "L'étoile",
    "indonesian": "Bintang",
    "malay": "Bintang",
    "urdu": "তারা",
    "bengali": "ستارہ",
    "place": "Makkah",
    "arabic": "النجم"
  },
  {
    "id": 54,
    "name": "Al Qamar",
    "aya": 55,
    "english": "The Moon",
    "turkish": "Kamer",
    "french": "La Lune",
    "indonesian": "Bulan",
    "malay": "Bulan",
    "urdu": "চাঁদ",
    "bengali": "چاند",
    "place": "Makkah",
    "arabic": "القمر"
  },
  {
    "id": 55,
    "name": "Ar Rahman",
    "aya": 78,
    "english": "The Most Merciful",
    "turkish": "Rahmân",
    "french": "Le Tout Miséricordieux",
    "indonesian": "Yang Maha Pemurah",
    "malay": "Yang Maha Pemurah",
    "urdu": "পরম করুণাময়",
    "bengali": "مہربان",
    "place": "Madinah",
    "arabic": "الرحمن"
  },
  {
    "id": 56,
    "name": "Al Waqiah",
    "aya": 96,
    "english": "The Inevitable",
    "turkish": "Vâkıa",
    "french": "L'évenement",
    "indonesian": "Hari Kiamat",
    "malay": "Peristiwa yang Tidak Dapat Dielakkan",
    "urdu": "নিশ্চিত ঘটনা",
    "bengali": "واقعہ ہونے والی قیامت",
    "place": "Makkah",
    "arabic": "الواقعة"
  },
  {
    "id": 57,
    "name": "Al Hadeed",
    "aya": 29,
    "english": "The Iron",
    "turkish": "Hadîd",
    "french": "Le fer",
    "indonesian": "Besi",
    "malay": "Besi",
    "urdu": "লোহা",
    "bengali": "فولاد",
    "place": "Madinah",
    "arabic": "الحديد"
  },
  {
    "id": 58,
    "name": "Al Mujadila",
    "aya": 22,
    "english": "The Pleading",
    "turkish": "Mücâdele",
    "french": "La discution",
    "indonesian": "Wanita yang Menggugat",
    "malay": "Perempuan yang Merayu",
    "urdu": "অনুযোগকারিণী",
    "bengali": "جھگڑنے والی",
    "place": "Madinah",
    "arabic": "المجادلة"
  },
  {
    "id": 59,
    "name": "Al Hashr",
    "aya": 24,
    "english": "The Mustering",
    "turkish": "Haşr",
    "french": "L'exode",
    "indonesian": "Pengusiran",
    "malay": "Pengusiran",
    "urdu": "সমাবেশ",
    "bengali": "حشر",
    "place": "Madinah",
    "arabic": "الحشر"
  },
  {
    "id": 60,
    "name": "Al Mumtahanah",
    "aya": 13,
    "english": "The Examined One",
    "turkish": "Mümtehine",
    "french": "L'éprouvée",
    "indonesian": "Wanita yang Diuji",
    "malay": "Perempuan yang Diuji",
    "urdu": "নারী, যাকে পরীক্ষা করা হবে",
    "bengali": "امتحان لی جانے والی",
    "place": "Madinah",
    "arabic": "الممتحنة"
  },
  {
    "id": 61,
    "name": "As Saff",
    "aya": 14,
    "english": "The Ranks",
    "turkish": "Saff",
    "french": "Le rang",
    "indonesian": "Barisan",
    "malay": "Barisan",
    "urdu": "সারিবদ্ধ সৈন্যদল",
    "bengali": "صف",
    "place": "Madinah",
    "arabic": "الصف"
  },
  {
    "id": 62,
    "name": "Al Jumu'ah",
    "aya": 11,
    "english": "Congregation (Friday)",
    "turkish": "Cuma",
    "french": "Le vendredi",
    "indonesian": "Hari Jum\\'at",
    "malay": "Hari Jumaat",
    "urdu": "সম্মেলন/শুক্রবার",
    "bengali": "جمعہ",
    "place": "Madinah",
    "arabic": "الجمعة"
  },
  {
    "id": 63,
    "name": "Al Munafiqoon",
    "aya": 11,
    "english": "The Hypocrites",
    "turkish": "Münâfikûn",
    "french": "Les hypocrites",
    "indonesian": "Kaum Munafik",
    "malay": "Golongan Munafik",
    "urdu": "ভণ্ড বিশ্বাসী",
    "bengali": "منافقین",
    "place": "Madinah",
    "arabic": "المنافقون"
  },
  {
    "id": 64,
    "name": "At Taghabun",
    "aya": 18,
    "english": "The Cheating",
    "turkish": "Tegâbün",
    "french": "La grande perte",
    "indonesian": "Hari Dinampakkan Kesalahan",
    "malay": "Dinampakkan Kesalahan",
    "urdu": "মোহ অপসারণ",
    "bengali": "ہار جیت",
    "place": "Madinah",
    "arabic": "التغابن"
  },
  {
    "id": 65,
    "name": "At Talaq",
    "aya": 12,
    "english": "Divorce",
    "turkish": "Talâk",
    "french": "Le divorce",
    "indonesian": "Perceraian",
    "malay": "Cerai / Talak",
    "urdu": "তালাক",
    "bengali": "طلاق",
    "place": "Madinah",
    "arabic": "الطلاق"
  },
  {
    "id": 66,
    "name": "At Tahreem",
    "aya": 12,
    "english": "The Prohibition",
    "turkish": "Tahrîm",
    "french": "L'interdiction",
    "indonesian": "Mengharamkan",
    "malay": "Mengharamkan",
    "urdu": "নিষিদ্ধকরণ",
    "bengali": "حرمت",
    "place": "Madinah",
    "arabic": "التحريم"
  },
  {
    "id": 67,
    "name": "Al Mulk",
    "aya": 30,
    "english": "The Dominion",
    "turkish": "Mülk",
    "french": "La royauté",
    "indonesian": "Kerajaan",
    "malay": "Kerajaan",
    "urdu": "সার্বভৌম কর্তৃত্ব",
    "bengali": "بادشاہ",
    "place": "Makkah",
    "arabic": "الملك"
  },
  {
    "id": 68,
    "name": "Al Qalam",
    "aya": 52,
    "english": "The Pen",
    "turkish": "Kalem",
    "french": "La plume",
    "indonesian": "Pena",
    "malay": "Pena / Kalam",
    "urdu": "কলম",
    "bengali": "قلم",
    "place": "Makkah",
    "arabic": "القلم"
  },
  {
    "id": 69,
    "name": "Al Haaqqah",
    "aya": 52,
    "english": "The Sure Reality",
    "turkish": "Hâkka",
    "french": "Celle qui montre la vérité",
    "indonesian": "Kenyataan (Hari Kiamat)",
    "malay": "Keadaan Sebenar / Hari Kiamat",
    "urdu": "নিশ্চিত সত্য",
    "bengali": "حق ہونے والی",
    "place": "Makkah",
    "arabic": "الحاقة"
  },
  {
    "id": 70,
    "name": "Al Ma'arij",
    "aya": 44,
    "english": "The Ways of Ascent",
    "turkish": "Meâric",
    "french": "Les voies d'ascension",
    "indonesian": "Tempat yang Naik",
    "malay": "Tempat-tempat Naik",
    "urdu": "উন্নয়নের সোপান",
    "bengali": "عروج",
    "place": "Makkah",
    "arabic": "المعارج"
  },
  {
    "id": 71,
    "name": "Nooh",
    "aya": 28,
    "english": "Noah",
    "turkish": "Nûh",
    "french": "Noé",
    "indonesian": "Nuh",
    "malay": "Nabi Nuh a.s.",
    "urdu": "নবী নূহ",
    "bengali": "نوح",
    "place": "Makkah",
    "arabic": "نوح"
  },
  {
    "id": 72,
    "name": "Al Jinn",
    "aya": 28,
    "english": "The Jinn",
    "turkish": "Cin",
    "french": "Les Djinns",
    "indonesian": "Jin",
    "malay": "Jin",
    "urdu": "জিন সম্প্রদায়",
    "bengali": "جن",
    "place": "Makkah",
    "arabic": "الجن"
  },
  {
    "id": 73,
    "name": "Al Muzammil",
    "aya": 20,
    "english": "The Enfolded One",
    "turkish": "Müzzemmil",
    "french": "L'enveloppé",
    "indonesian": "Orang yang Berselimut",
    "malay": "Yang Berselimut",
    "urdu": "বস্ত্রাচ্ছাদনকারী",
    "bengali": "کپڑا لپیٹنے والا",
    "place": "Makkah",
    "arabic": "المزمل"
  },
  {
    "id": 74,
    "name": "Al Muddathir",
    "aya": 56,
    "english": "The One Wrapped Up",
    "turkish": "Müddessir",
    "french": "Le revêtu d'un manteau",
    "indonesian": "Orang yang Berkemul",
    "malay": "Yang Berselubung",
    "urdu": "পোশাক পরিহিত",
    "bengali": "کپڑا اوڑھنے والا",
    "place": "Makkah",
    "arabic": "المدثر"
  },
  {
    "id": 75,
    "name": "Al Qiyamah",
    "aya": 40,
    "english": "Resurrection",
    "turkish": "Kıyâmet",
    "french": "La résurrection",
    "indonesian": "Hari Berbangkit",
    "malay": "Hari Kebangkitan / Kiamat",
    "urdu": "পুনরুত্থান",
    "bengali": "قیامۃ",
    "place": "Makkah",
    "arabic": "القيامة"
  },
  {
    "id": 76,
    "name": "Al Insaan",
    "aya": 31,
    "english": "The Human",
    "turkish": "İnsân",
    "french": "L'homme",
    "indonesian": "Manusia",
    "malay": "Manusia",
    "urdu": "মানবজাতি",
    "bengali": "انسان",
    "place": "Madinah",
    "arabic": "الانسان"
  },
  {
    "id": 77,
    "name": "Al Mursalat",
    "aya": 50,
    "english": "Those Sent Forth",
    "turkish": "Mürselât",
    "french": "Les envoyés",
    "indonesian": "Malaikat-malaikan yang Diutus",
    "malay": "Malaikat Yang Diutus",
    "urdu": "প্রেরিত পুরুষ",
    "bengali": "بھیجی جانے والی ہوائیں",
    "place": "Makkah",
    "arabic": "المرسلات"
  },
  {
    "id": 78,
    "name": "An Naba",
    "aya": 40,
    "english": "The Great News",
    "turkish": "Nebe",
    "french": "La nouvelle",
    "indonesian": "Berita Besar",
    "malay": "Berita Besar",
    "urdu": "মহাসংবাদ",
    "bengali": "خبر",
    "place": "Makkah",
    "arabic": "النبأ"
  },
  {
    "id": 79,
    "name": "An Naaziat",
    "aya": 46,
    "english": "Those Who Tear Out",
    "turkish": "Naziât",
    "french": "Les anges qui arrachent les âmes",
    "indonesian": "Malaikat yang Mencabut",
    "malay": "Malaikat Yang Mencabut",
    "urdu": "প্রচেষ্টাকারী",
    "bengali": "زور سے کھینچنے والے",
    "place": "Makkah",
    "arabic": "النازعات"
  },
  {
    "id": 80,
    "name": "Abasa",
    "aya": 42,
    "english": "He Frowned",
    "turkish": "Abese",
    "french": "Il s'est renfrogné",
    "indonesian": "Ia Bermuka Masam",
    "malay": "Dia Bermasam Muka",
    "urdu": "সে ভ্রু কুঁচকালো",
    "bengali": "تیوری چڑہائی",
    "place": "Makkah",
    "arabic": "عبس"
  },
  {
    "id": 81,
    "name": "At Takweer",
    "aya": 29,
    "english": "The Folding Up",
    "turkish": "Tekvîr",
    "french": "L'obscurcissement",
    "indonesian": "Menggulung",
    "malay": "Menggulung",
    "urdu": "অন্ধকারাচ্ছন্ন",
    "bengali": "لپیٹنا",
    "place": "Makkah",
    "arabic": "التكوير"
  },
  {
    "id": 82,
    "name": "Al Infitar",
    "aya": 19,
    "english": "The Overthrowing",
    "turkish": "İnfitâr",
    "french": "La rupture",
    "indonesian": "Terbelah",
    "malay": "Terpecah & Terbelah",
    "urdu": "বিদীর্ণ করা",
    "bengali": "ٹکڑے ہونا",
    "place": "Makkah",
    "arabic": "الإنفطار"
  },
  {
    "id": 83,
    "name": "Al Mutaffifin",
    "aya": 36,
    "english": "The Cleaving Asunder",
    "turkish": "Mutaffifîn",
    "french": "Les fraudeurs",
    "indonesian": "Orang-orang Curang",
    "malay": "Golongan yang Curang",
    "urdu": "প্রতারণা করা",
    "bengali": "ناپ تول میں کمی کرنے والے",
    "place": "Makkah",
    "arabic": "المطففين"
  },
  {
    "id": 84,
    "name": "Al Inshiqaaq",
    "aya": 25,
    "english": "The Dealers in Fraud",
    "turkish": "İnşikâk",
    "french": "La déchirure",
    "indonesian": "Terbelah",
    "malay": "Terbelah",
    "urdu": "খণ্ড-বিখণ্ডকরণ",
    "bengali": "پھٹنا",
    "place": "Makkah",
    "arabic": "الإنشقاق"
  },
  {
    "id": 85,
    "name": "Al Burooj",
    "aya": 22,
    "english": "The Constellations",
    "turkish": "Burûc",
    "french": "Les constellations",
    "indonesian": "Gugusan Bintang",
    "malay": "Gugusan Bintang",
    "urdu": "নক্ষত্রপুঞ্জ",
    "bengali": "برج",
    "place": "Makkah",
    "arabic": "البروج"
  },
  {
    "id": 86,
    "name": "At Taariq",
    "aya": 17,
    "english": "The Morning Star",
    "turkish": "Târık",
    "french": "L'astre nocturne",
    "indonesian": "Yang Datang di Malam Hari",
    "malay": "Pengunjung Malam",
    "urdu": "রাতের আগন্তুক",
    "bengali": "رات کو آنے والا",
    "place": "Makkah",
    "arabic": "الطارق"
  },
  {
    "id": 87,
    "name": "Al A'laa",
    "aya": 19,
    "english": "The Most High",
    "turkish": "A'lâ",
    "french": "Le Très-Haut",
    "indonesian": "Yang Paling Tinggi",
    "malay": "Yang Tertinggi",
    "urdu": "সর্বোন্নত",
    "bengali": "اعلی",
    "place": "Makkah",
    "arabic": "الأعلى"
  },
  {
    "id": 88,
    "name": "Al Ghaashiyah",
    "aya": 26,
    "english": "The Overwhelming Event",
    "turkish": "Gâşiye",
    "french": "L'enveloppante",
    "indonesian": "Hari Pembalasan",
    "malay": "Peristiwa Menggelisahkan/Hari Pembalasan",
    "urdu": "বিহ্বলকর ঘটনা",
    "bengali": "چھا جانے والی",
    "place": "Makkah",
    "arabic": "الغاشية"
  },
  {
    "id": 89,
    "name": "Al Fajr",
    "aya": 30,
    "english": "The Daybreak",
    "turkish": "Fecr",
    "french": "L'aube",
    "indonesian": "Fajar",
    "malay": "Fajar / Sinar Mentari",
    "urdu": "ভোরবেলা",
    "bengali": "فجر",
    "place": "Makkah",
    "arabic": "الفجر"
  },
  {
    "id": 90,
    "name": "Al Balad",
    "aya": 20,
    "english": "The City",
    "turkish": "Beled",
    "french": "La cité",
    "indonesian": "Negeri",
    "malay": "Negeri",
    "urdu": "নগর",
    "bengali": "شہر",
    "place": "Makkah",
    "arabic": "البلد"
  },
  {
    "id": 91,
    "name": "Ash Shams",
    "aya": 15,
    "english": "The Sun",
    "turkish": "Şems",
    "french": "Le Soleil",
    "indonesian": "Matahari",
    "malay": "Matahari",
    "urdu": "সূর্য",
    "bengali": "آفتاب",
    "place": "Makkah",
    "arabic": "الشمس"
  },
  {
    "id": 92,
    "name": "Al Layl",
    "aya": 21,
    "english": "The Night",
    "turkish": "Leyl",
    "french": "La nuit",
    "indonesian": "Malam",
    "malay": "Malam",
    "urdu": "রাত",
    "bengali": "رات",
    "place": "Makkah",
    "arabic": "الليل"
  },
  {
    "id": 93,
    "name": "Ad Dhuha",
    "aya": 11,
    "english": "The Glorious Morning Light",
    "turkish": "Duhâ",
    "french": "Le jour montant",
    "indonesian": "Waktu Dhuha",
    "malay": "Pagi yang Cemerlang / Matahari Meninggi",
    "urdu": "পূর্বাহ্নের সুর্যকিরণ",
    "bengali": "دن کا چڑھنا",
    "place": "Makkah",
    "arabic": "الضحى"
  },
  {
    "id": 94,
    "name": "Ash Sharh",
    "aya": 8,
    "english": "The Opening Up of the Heart",
    "turkish": "İnşirâh",
    "french": "L'ouverture",
    "indonesian": "Melapangkan",
    "malay": "Melapangkan",
    "urdu": "বক্ষ প্রশস্তকরণ",
    "bengali": "تسکین",
    "place": "Makkah",
    "arabic": "الشرح"
  },
  {
    "id": 95,
    "name": "At Teen",
    "aya": 8,
    "english": "The Fig Tree",
    "turkish": "Tîn",
    "french": "Le figuier",
    "indonesian": "Buah Tin",
    "malay": "Buah Tin / Buah Ara",
    "urdu": "ডুমুর",
    "bengali": "انجیر",
    "place": "Makkah",
    "arabic": "التين"
  },
  {
    "id": 96,
    "name": "Al Alaq",
    "aya": 19,
    "english": "The Clinging Clot",
    "turkish": "Alak",
    "french": "L'adhérence",
    "indonesian": "Segumpal Darah",
    "malay": "Segumpal Darah",
    "urdu": "রক্তপিণ্ড",
    "bengali": "جما ہوا خون",
    "place": "Makkah",
    "arabic": "العلق"
  },
  {
    "id": 97,
    "name": "Al Qadr",
    "aya": 5,
    "english": "The Night of Honor",
    "turkish": "Kadir",
    "french": "La destinée",
    "indonesian": "Kemuliaan",
    "malay": "Kemuliaan",
    "urdu": "মহিমান্বিত",
    "bengali": "شب قدر",
    "place": "Makkah",
    "arabic": "القدر"
  },
  {
    "id": 98,
    "name": "Al Bayyinah",
    "aya": 8,
    "english": "The Clear Evidence",
    "turkish": "Beyyine",
    "french": "La preuve",
    "indonesian": "Pembuktian",
    "malay": "Bukti yang Nyata",
    "urdu": "প্রমাণ",
    "bengali": "ثبوت",
    "place": "Madinah",
    "arabic": "البينة"
  },
  {
    "id": 99,
    "name": "Az Zalzalah",
    "aya": 8,
    "english": "The Earthquake",
    "turkish": "Zilzâl",
    "french": "La secousse",
    "indonesian": "Kegoncangan",
    "malay": "Kegoncangan",
    "urdu": "ভূমিকম্প",
    "bengali": "زلزلہ",
    "place": "Madinah",
    "arabic": "الزلزلة"
  },
  {
    "id": 100,
    "name": "Al Aadiyaat",
    "aya": 11,
    "english": "The Courser",
    "turkish": "Âdiyât",
    "french": "Les coursiers",
    "indonesian": "Berlari Kencang",
    "malay": "Yang Berlari Kencang",
    "urdu": "অভিযানকারী",
    "bengali": "دوڑنے والے گھوڑے",
    "place": "Makkah",
    "arabic": "العاديات"
  },
  {
    "id": 101,
    "name": "Al Qaari'ah",
    "aya": 11,
    "english": "The Striking Hour",
    "turkish": "Kâria",
    "french": "Le fracas",
    "indonesian": "Hari Kiamat",
    "malay": "Hari Yang Hingar Bingar / Kiamat",
    "urdu": "মহাসংকট",
    "bengali": "کھڑکھڑاہٹ",
    "place": "Makkah",
    "arabic": "القارعة"
  },
  {
    "id": 102,
    "name": "At Takaathur",
    "aya": 8,
    "english": "The Piling Up",
    "turkish": "Tekâsür",
    "french": "La course aux richesses",
    "indonesian": "Bermegah-megahan",
    "malay": "Bermegah-megah",
    "urdu": "প্রাচুর্যের প্রতিযোগিতা",
    "bengali": "کثرت",
    "place": "Makkah",
    "arabic": "التكاثر"
  },
  {
    "id": 103,
    "name": "Al Asr",
    "aya": 3,
    "english": "The Time",
    "turkish": "Asr",
    "french": "Le temps",
    "indonesian": "Waktu Sore",
    "malay": "Masa",
    "urdu": "সময়",
    "bengali": "زمانہ",
    "place": "Makkah",
    "arabic": "العصر"
  },
  {
    "id": 104,
    "name": "Al Humazah",
    "aya": 9,
    "english": "The Scandalmonger",
    "turkish": "Hümeze",
    "french": "Les calomniateurs",
    "indonesian": "Pengumpat",
    "malay": "Pengumpat",
    "urdu": "পরনিন্দাকারী",
    "bengali": "عیب لگانے والا",
    "place": "Makkah",
    "arabic": "الهمزة"
  },
  {
    "id": 105,
    "name": "Al Feel",
    "aya": 5,
    "english": "The Elephant",
    "turkish": "Fîl",
    "french": "L'éléphant",
    "indonesian": "Gajah",
    "malay": "Gajah",
    "urdu": "হাতি",
    "bengali": "ہاتھی",
    "place": "Makkah",
    "arabic": "الفيل"
  },
  {
    "id": 106,
    "name": "Quraysh",
    "aya": 4,
    "english": "The Quraysh",
    "turkish": "Kureyş",
    "french": "Coraïsh",
    "indonesian": "Suku Quraisy",
    "malay": "Kaum Quraisy",
    "urdu": "কুরাইশ গোত্র",
    "bengali": "قریش",
    "place": "Makkah",
    "arabic": "قريش"
  },
  {
    "id": 107,
    "name": "Al Maa'oon",
    "aya": 7,
    "english": "The Neighbourly Assistance",
    "turkish": "Maûn",
    "french": "L'ustensile",
    "indonesian": "Barang yang Berguna",
    "malay": "Barangan Berguna",
    "urdu": "সাহায্য সহায়তা",
    "bengali": "تھوڑی سی چیز",
    "place": "Makkah",
    "arabic": "الماعون"
  },
  {
    "id": 108,
    "name": "Al Kawthar",
    "aya": 3,
    "english": "Abundance",
    "turkish": "Kevser",
    "french": "l'abondance",
    "indonesian": "Nikmat Berlimpah",
    "malay": "Sungai Di Syurga",
    "urdu": "কাউসার/প্রাচুর্য",
    "bengali": "جنت کی نہر",
    "place": "Makkah",
    "arabic": "الكوثر"
  },
  {
    "id": 109,
    "name": "Al Kaafiroon",
    "aya": 6,
    "english": "The Disbelievers",
    "turkish": "Kâfirûn",
    "french": "Les infidèles",
    "indonesian": "Orang-orang Kafir",
    "malay": "Golongan Kafir",
    "urdu": "অবিশ্বাসী",
    "bengali": "کافرین",
    "place": "Makkah",
    "arabic": "الكافرون"
  },
  {
    "id": 110,
    "name": "An Nasr",
    "aya": 3,
    "english": "The Help",
    "turkish": "Nasr",
    "french": "Les secours",
    "indonesian": "Pertolongan",
    "malay": "Pertolongan",
    "urdu": "সাহায্য",
    "bengali": "نصرت",
    "place": "Madinah",
    "arabic": "النصر"
  },
  {
    "id": 111,
    "name": "Al Masad",
    "aya": 5,
    "english": "The Plaited Rope",
    "turkish": "Tebbet",
    "french": "Les fibres",
    "indonesian": "Gejolak Api (Sabut)",
    "malay": "Nyalaan Api",
    "urdu": "খেজুরের পাকানো (রশি)",
    "bengali": "خوب بٹی ہوئی",
    "place": "Makkah",
    "arabic": "المسد"
  },
  {
    "id": 112,
    "name": "Al Ikhlaas",
    "aya": 4,
    "english": "Purity of Faith",
    "turkish": "İhlâs",
    "french": "Le monothéisme pur",
    "indonesian": "Ikhlash",
    "malay": "Tulus Ikhlas / Memurnikan Keesaan Allah",
    "urdu": "আন্তরিকতা",
    "bengali": "اخلاص",
    "place": "Makkah",
    "arabic": "الإخلاص"
  },
  {
    "id": 113,
    "name": "Al Falaq",
    "aya": 5,
    "english": "The Rising Dawn",
    "turkish": "Felak",
    "french": "L'aube naissante",
    "indonesian": "Waktu Shubuh",
    "malay": "Waktu Subuh / Dinihari",
    "urdu": "নিশিভোর",
    "bengali": "صبح",
    "place": "Makkah",
    "arabic": "الفلق"
  },
  {
    "id": 114,
    "name": "An Naas",
    "aya": 6,
    "english": "Mankind",
    "turkish": "Nâs",
    "french": "Les hommes",
    "indonesian": "Umat Manusia",
    "malay": "Manusia",
    "urdu": "মানুষ জাতি",
    "bengali": "انسان",
    "place": "Makkah",
    "arabic": "الناس"
  }
];
